### PR TITLE
Update travis, gemspec for different rails versions

### PR DESCRIPTION
**Pull request by agau4779**

### CODE REVIEW

**Comment by camertron** [comment]
Is it possible to delete the dummy app?

**Comment by agau4779** [comment]
@camertron hmm, it looks like we can't get rid of the dummy app as some Konacha specs live in there. I did manage to get Travis to run the konacha specs as well.

I'm having trouble making this compatible with both Rails 3.2.19 and Rails 4 - because while Rails 4 includes the `strong_parameters` gem, Rails 3 doesn't. I can't seem to figure out how to conditionally install `strong_parameters` if the Rails version is <4, so I'm thinking this should be pushed as v 2.0.0 with a note that it's not backwards-compatible with Rails 3.

**Comment by camertron** [comment]
Oh man yeah... the `strong_parameters` vs `protected_attributes` gem has been SUCH a pain on a number of projects. I think there's no choice but to release a Rails 4-only version (don't forget to bump the major).

**Comment by camertron** [comment]
I think bartt-ssl_requirement isn't compatible with Rails 4?

**Comment by camertron** [comment]
@agau4779 and I talked offline and decided the thing to do is wait until we figure out how we're going to address the SSL requirement stuff. My hunch is there's a built-in way to do this in Rails 4, or we might have to dedicate some time to upgrading the ssl_requirement gem.

**Comment by camertron** [comment]
Alright, so what's the deal with ssl_requirement? It doesn't look like this PR removes or upgrades it.

**Comment by camertron** [comment]
Wait... ssl_requirement isn't in the Gemfile or gemspec. Maybe I'm crazy?

**Comment by camertron** [comment]
@agau4779 explained that the ssl_requirement stuff was handled in a different PR. Which means: :+1:

**Pull request merged**
