### PR TITLE
remove sslrequirement

### PR DESCRIPTION
**Pull request by agau4779**
bartt-sslrequirement is not compatible with Rails 4 or versions of Ruby < 2. See [bartt-ssl_requirement readme](https://github.com/bartt/ssl_requirement)

It looks like since this is a project that includes Rails 3, we should be using [force_ssl](http://apidock.com/rails/ActionController/ForceSSL/ClassMethods/force_ssl) for any methods that have to be in SSL (`ssl_required` in bartt-ssl_requirement).

It also doesn't look like we're using it here in any way here besides `ssl_allowed :show` in jobs_controller.

### CODE REVIEW

**Comment by agau4779** [comment]
Hey @azach does this make sense? Do you know if ssl_requirement is strictly required for resque-poll to function?

**Comment by azach** [comment]
I think without it the https was redirecting to http or something, which led the polling function to not work. I think.

**Comment by agau4779** [comment]
Verified working on BPT and lumos_rails in staging.

**Comment by azach** [comment]
:+1:

**Pull request merged**
